### ISSUE TITLE
SplashScreen does not hide if authentication_data is null

### ISSUE THREAD

**Issue by ErnestoFGonzalez** [hunchat/hunchat-app#11]
`SplashScreen` does not hide if `authentication_data` is null.

```
...
class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      isFirstLaunch: false,
      appIsReady: false,
      visible:
        Platform.OS === "ios" && Platform.Version === "14.0" ? true : false,
    };
  }

  componentDidMount() {
    StatusBar.setBarStyle("light-content");
    if (Platform.OS === "android") {
      StatusBar.setBackgroundColor("rgba(0,0,0,0)");
      StatusBar.setTranslucent(true);
    }
  }

  componentDidUpdate(prevProps) {
    if (this.props.authRefreshToken !== prevProps.authRefreshToken) {
      setTimeout(function () {
        SplashScreen.hideAsync()
      }, 500); // 500 ms delay to allow AppStack.Navigator to mount screens
    }
  }

  /**
   * Method that serves to load resources and make API calls
   */
  prepareResources = async () => {
    const authData = await loadAuthData();
    const isFirstLaunch = await checkIfFirstLaunch();
    this.setState({ isFirstLaunch });
    return Promise.all([authData, isFirstLaunch])
  };

  onPressUpdate = () => {
    Linking.openURL("App-prefs:root=General");
  };

  render() {
    if (!this.state.appIsReady) {
      return (
        <AppLoading
          startAsync={this.prepareResources}
          onFinish={() => this.setState({ appIsReady: true })}
          onError={console.warn}
          autoHideSplash={false}
        />
      );
    }

    return (
      <NavigationContainer ref={navigationRef}>
        {/* Alert of problem with iOS 14.0 */}
        {/* iOS 14.0 causes a break on expo-av.Video. See https://github.com/expo/expo/issues/10249 */}
        <Dialog.Container visible={this.state.visible}>
          <Dialog.Title>Please update your software</Dialog.Title>
          <Dialog.Description>
            You are using iOS 14.0. Hunchat doesn't like this version. Make
            Hunchat happy and update.
          </Dialog.Description>
          <Dialog.Button label="Update" onPress={this.onPressUpdate} />
        </Dialog.Container>

        <AppStack
          authRefreshToken={this.props.authRefreshToken}
          isFirstLaunch={this.state.isFirstLaunch}
        />
      </NavigationContainer>
    );
  }
}

const mapStateToProps = (state) => ({
  authRefreshToken: state.auth.refreshToken,
});

export default connect(mapStateToProps)(App);
```
`SplashScreen.hideAsync()` is only executed inside `componendDidUpdate` after checking if `props.authRefreshToken` updated. This works if `authentication_data` is populated, but fails to hide the `SplashScreen` otherwise.

**Comment by mikenath223** [comment]
Hi,

So I found 2 workarounds for it.

This is the first workaround:
One can completely remove the componentDidUpdate method(since its only purpose is to hide the SplashScreen) and next set the timeout in the componentDidMount. This is because the action to hide the SplashScreen is carried out both if the user has auth tokens or not.
Here is the first:
```
class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      isFirstLaunch: false,
      appIsReady: false,
      visible:
        Platform.OS === "ios" && Platform.Version === "14.0" ? true : false,
    };
  }

  componentDidMount() {
    StatusBar.setBarStyle("light-content");
    if (Platform.OS === "android") {
      StatusBar.setBackgroundColor("rgba(0,0,0,0)");
      StatusBar.setTranslucent(true);
    }
    setTimeout(function () {
      SplashScreen.hideAsync()
    }, 500);
  }
```

The second workaround is this:
If one doesn't want to remove the componentDidUpdate method you can set the timeout in the componentDidMount and if the user has auth tokens this would trigger the componentDidUpdate which when it runs would first clear the first timeout and set a new timeout.
Here is the second:
```
class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      isFirstLaunch: false,
      appIsReady: false,
      visible:
        Platform.OS === "ios" && Platform.Version === "14.0" ? true : false,
    };
  }

  componentDidMount() {
    StatusBar.setBarStyle("light-content");
    if (Platform.OS === "android") {
      StatusBar.setBackgroundColor("rgba(0,0,0,0)");
      StatusBar.setTranslucent(true);
    }
    this.splashCountDown = setTimeout(function () {
      SplashScreen.hideAsync()
    }, 500);
  }

  componentDidUpdate(prevProps) {
    if (this.props.authRefreshToken !== prevProps.authRefreshToken) {
      clearTimeout(this.splashCountDown)
      setTimeout(function () {
        SplashScreen.hideAsync()
      }, 500); // 500 ms delay to allow AppStack.Navigator to mount screens
    }
  }

```

Happy Coding 🙂

**Comment by ErnestoFGonzalez** [comment]
@mikenath223 I just tried your workarounds and they seem to work. Except the 500ms timeout isn't enough time in this case for `AppStack` to update after receiving the new `refreshToken` as props. At least on my device. Do you think this timer is a good option? Since for different devices the time may vary.

**Comment by mikenath223** [comment]
Alright.

That's true there would be inconsistencies in the timer on different devices.

One way to fix this that eliminates the need for setTimeout is to reconfigure the backend to always return a value irrespective of whether the user is authenticated(in which case it returns refresh tokens) or not authenticated(in which case it returns a message that the user isn't authenticated). Then in that way, we are always certain of the props being updated and so we can simply wait for the props to change and when it does then we hide the SplashScreen.

This way:
```
...
class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      isFirstLaunch: false,
      appIsReady: false,
      visible:
        Platform.OS === "ios" && Platform.Version === "14.0" ? true : false,
    };
  }

  componentDidMount() {
    StatusBar.setBarStyle("light-content");
    if (Platform.OS === "android") {
      StatusBar.setBackgroundColor("rgba(0,0,0,0)");
      StatusBar.setTranslucent(true);
    }
  }

  componentDidUpdate(prevProps) {
    if (this.props.authResp) {
        SplashScreen.hideAsync()
       // then handle the different cases where the auth response has a message that 
      // the user isn't auth(in which case login screen is shown) or if the auth response contains 
      // the authRefreshToken then show user dashboard).
    }
  }
...
```

Those are my thoughts. Perhaps there are other ways to handle this.

Thanks.

**Comment by ErnestoFGonzalez** [comment]
@mikenath223, we already know when `loadAuthData` finished. Notice how `AppLoading` `onFinish` sets the `appIsReady` state. What we can't exactly determine in this scenario is the time it takes `AppStack` to push the new screens, in case the `props.refreshToken` updates. 
Note: If you remove the timer and pass `autoHideSplash={false}` to `AppLoading`, the `SplashScreen` will hide when the
`loadAuthData` finishes, but before the `AppStack` pushes to the new (authenticated) screens.

**Comment by mikenath223** [comment]
Yea that's true I can see how that poses an issue because the SplashScreen hiding
  before the AppStack pushes the new screens would mean the user would be shown the 
  wrong screen for a brief period which would impact the user experience.

  So my idea is to use the [React Native Bundle Splitter](https://kirillzyusko.github.io/react-native-bundle-splitter/docs/getting-started)  package, particularly with the Navigation libraries integration we could group the authenticated stack in a single group and preload it, thereby reducing the load time of the new screens on AppStack.

  [Here](https://kirillzyusko.github.io/react-native-bundle-splitter/docs/async-loading) is the screens async loading guide on the docs, it shows an example of grouping screens.
  [Here](https://snack.expo.io/frQvTTGIP) is a snackbar example of integrating with @react-navigation.

  So essentially we group the authenticated screens and preload them.

**Comment by ErnestoFGonzalez** [comment]
> Yea that's true I can see how that poses an issue because the SplashScreen hiding
> before the AppStack pushes the new screens would mean the user would be shown the
> wrong screen for a brief period which would impact the user experience.
> 
> So my idea is to use the [React Native Bundle Splitter](https://kirillzyusko.github.io/react-native-bundle-splitter/docs/getting-started) package, particularly with the Navigation libraries integration we could group the authenticated stack in a single group and preload it, thereby reducing the load time of the new screens on AppStack.
> 
> [Here](https://kirillzyusko.github.io/react-native-bundle-splitter/docs/async-loading) is the screens async loading guide on the docs, it shows an example of grouping screens.
> [Here](https://snack.expo.io/frQvTTGIP) is a snackbar example of integrating with @react-navigation.
> 
> So essentially we group the authenticated screens and preload them.

That's a good approach. I had never heard of React Native Bundle Splitter. Thank you

**Comment by mikenath223** [comment]
Hi,

So the package React Native Bundle Splitter doesn't work with expo because of a feature that isn't supported in expo. [Here](https://kirillzyusko.github.io/react-native-bundle-splitter/docs/enabling-ram-bundle) it says that to implement preloading the RAM Bundle feature needs to be enabled on the build.gradle file. Which isn't on expo, and expo doesn't provide a way to enable it elsewhere. Even a feature request was made for it [here](https://expo.canny.io/feature-requests/p/faster-startup-with-ram-bundles), about 2 years ago but no decision yet on that. 
So essentially preloading the components would only work on standalone React Native, not on expo.

However, based on [an article by inVision](https://www.invisionapp.com/inside-design/splash-screens/), I feel setting the timeout is ok inasmuch as it stays below the recommended 3secs as stated in this screenshot from the article:
![ice_screenshot_20210323-001804](https://user-images.githubusercontent.com/33323077/112104545-a04cfa80-8bab-11eb-89bd-619720ae1da7.png)

So I basically just cleaned the component and set the timeout in the Promise.all array, so perhaps this doesn't count as a solution:
```
...
  /**
   * Method that serves to load resources and make API calls
   */
  prepareResources = async () => {
    const authData = await loadAuthData();
    const isFirstLaunch = await checkIfFirstLaunch();
    this.setState({ isFirstLaunch });
    //Method to return a new promise that gets passed in the Promise.all array
    const timeOut = () => new Promise(resolve => setTimeout(() => resolve(), 2500)) 
    return Promise.all([authData, isFirstLaunch, timeOut()])
  };

...


    if (!this.state.appIsReady) {
      return (
        <AppLoading
          startAsync={this.prepareResources}
          onFinish={() => this.setState({ appIsReady: true })}
          onError={console.warn}
          autoHideSplash  
          
          //Set autoHideSplash to true. No need to pass it as autoHideSplash={true}, 
          //because in React as stated [here]=>(https://reactjs.org/docs/jsx-in-depth.html#props-default-to-true), 
          //simply passing props without assigning a value to it makes it default to true, 
          //and not passing it at all makes it default to false
        />
      );
...
```

**Comment by ErnestoFGonzalez** [comment]
I'm closing this since we've changed to app start up setup
